### ISSUE TITLE
Chunking causing long running process and unresponsiveness on IE10/11

### ISSUE THREAD

**Issue by NamespaceValentine** [FineUploader/fine-uploader#1534] opened 2016-03-01 21:03 UTC
## Type of issue [REQUIRED]
Bug

## Uploader type [REQUIRED]
S3

### Fine Uploader version [REQUIRED]
5.4.1

### Browsers where the bug is reproducible [REQUIRED]
IE10 IE11

### Operating systems where the bug is reproducible [REQUIRED]
Windows 7, possibly others as well

### Exact steps required to reproduce the issue [REQUIRED]
1. Upload a large file (500mb is what we have been using) using chunked uploads to S3

### All of your Fine Uploader initialization JavaScript code [REQUIRED]
```
var ie = (function(){
    var undef,rv = -1; // Return value assumes failure.
    var ua = window.navigator.userAgent;
    var msie = ua.indexOf('MSIE ');
    var trident = ua.indexOf('Trident/');

    if (msie > 0) {
        // IE 10 or older => return version number
        rv = parseInt(ua.substring(msie + 5, ua.indexOf('.', msie)), 10);
    } else if (trident > 0) {
        // IE 11 (or newer) => return version number
        var rvNum = ua.indexOf('rv:');
        rv = parseInt(ua.substring(rvNum + 3, ua.indexOf('.', rvNum)), 10);
    }

    return ((rv > -1) ? rv : undef);
}());

var s3Uploader;

var cloudfrontMapping = {
  "[Env name]": {
      url: "[Cloudfront distro endpoint]",
      accessKey: "[Access Key]"
    }
  } 

  //This gets us an environment from the URL
  var hostEnv = window.location.hostname.split('.')[2];

  var getFineUploaderOptions = function(keyPrefix){
  return {
    element: document.getElementById('sr-fine-uploader'),
    template: 'qq-template-s3',
    request: {
      endpoint: cloudfrontMapping[hostEnv].url,
      accessKey: cloudfrontMapping[hostEnv].accessKey
    },
    cors: {
      expected:true,
      allowXdr:true,
      allowCors: true
    },
    chunking: {
      enabled:true,
      partSize: 10485760,
      concurrent: {
        enabled:ie?false:true
      }
    },
    objectProperties: {
      acl: 'bucket-owner-full-control',
      bucket: [Bucket here],
      host: [Host here],
      region: "us-west-2",
      serverSideEncryption: true,
      key: function(id){
        return keyPrefix() + s3Uploader.getName(id);
      }
    },
    signature: {
      endpoint: '/signature',
      version: 4
    },
    retry: {
      enableAuto: true,
      autoRetryNote: document.getElementById('retry-text').title+" {retryNum}/{maxAuto} ..."
    }
    validation: {
      sizeLimit: 1073741824
    }
  };
}
var keyPrefix = function(){
  var srDetails = document.getElementById('srDetails').getAttribute('data-params');
  return "id-" + srId + "/";
};
s3Uploader = new qq.s3.FineUploader(getFineUploaderOptions(keyPrefix));
```

### Detailed explanation of the problem [REQUIRED]
When trying to do a chunked upload to S3, IE browser becomes very unresponsive, even on non-concurrent, small chunks. A profile trace revealed that 80% of its time is spent in the _doProcessBlock in the cryptojs imported library.

**Comment by dbeg** [comment] 2016-03-01 21:07
Potentially a dupe of  #1519?

**Comment by NamespaceValentine** [comment] 2016-03-01 22:22
I dont think so, in this one concurrency is a non-factor, it is off, so it is not a race condition issue. This is on a chunk by chunk basis taking a hugely excessive amount of time to process the cryptojs function in IE exclusively. They look like two separate issues.

**Comment by rnicholus** [comment] 2016-03-02 15:43
There isn't much that can be done about the CPU usage here. This is a fundamental problem with the version 4 signing algorithm created by AWS. It requires Fine Uploader to hash each file chunk sent via the multipart upload API. This requires reading each chunk into memory and then calculating a SHA256 hash given the file bytes. For underpowered machines, this _will_ have a noticeable impact on the CPU.

I'm not seeing the level of non-responsiveness that you've described, and I suspect this is only an issue on slow machines. To prevent the UI thread from being affected by this hash generation, I can explore pushing the hash calculation into a web worker. However, this may not solve the issue you are seeing in IE10/11, since IE does not support passing an `ArrayBuffer` into a web worker without explicitly copying each byte over the wire.

Your best bet may involve one of the following workarounds:

- Don't use version 4 signatures
- Use a small chunk size (5 MiB) to avoid pegging the CPU for long continuous periods of time
- Ensure your users are utilizing more performant machines.

Sorry that there isn't a better answer to this. I am quite unhappy with Amazon's v4 signature algorithm myself, but there isn't much that can be done about it.

**Closed by rnicholus** 2016-03-02 15:43 UTC

**Comment by NamespaceValentine** [comment] 2016-03-02 16:33
Thank you for the explanation.

**Comment by rnicholus** [comment] 2016-03-02 17:07
Curious: why are you disabling concurrent chunking in IE?

**Comment by NamespaceValentine** [comment] 2016-03-02 17:10
Without the concurrent chunking the issue did not occur, the uploads went smoothly with no spike in CPU. As our temporary workaround for a more long term solution that was the way we went. Our next steps will be to test against 5mb chunks, if that does not fix it, we will determine if v2 signing is a valid method.

**Comment by rnicholus** [comment] 2016-03-02 17:13
As long as you aren't uploading to any v4-exclusive regions, then there is no need to use v4 signatures. There's aren't many v4-exclusive regions at the moment. Frankfurt is one though. Also, concurrent chunking is not a factor here. If you're seeing the issue with one file and concurrent chunking enabled, you'll also see it with multiple in-progress files with concurrent chunking disabled.

You can also eliminate the entire `cors` section of your config. It's not needed unless your delete/signature endpoints reside on a different domain (yours don't).

**Comment by NamespaceValentine** [comment] 2016-03-02 17:25
Our signature is proxied to another server, without the cors section the headers for the proxy do not get set appropriately in the case of IE9.

**Comment by rnicholus** [comment] 2016-03-02 17:28
Which headers? It seems a bit odd that you must use `XDomainRequest` to send a request to a same-origin endpoint. The fact that it is proxied server-side shouldn't effect the request sent by Fine Uploader.

**Comment by NamespaceValentine** [comment] 2016-03-02 17:33
Our current routing pattern is a bit weird due to current constraints, our apache server is too old currently to correctly route https requests to AWS which require the SNI protocols that older Apache does not support. Due to this we hit a route on the server that proxies to a NodeJS proxy which proxies using https to our signing method which is fronted by AWS ApiGateway. In the NodeJS proxy, we set the host properly, and add the content-type in the cases where it was not set by the fineuploader request (ie9). However, there were still cors issue with the flow when we tried it that allowing the cors components in fineuploader to solve. Its possible our proxy could manipulate the headers as needed, but we were not able to devote the time to discovering the issue during this setup.

**Comment by NamespaceValentine** [comment] 2016-03-02 17:45
As a clarification to your earlier point about concurrent chunking, you are correct, it was the disabling of chunking altogether that fixed the issue, the reason concurrent was disabled was that we tried that as a first step (chunking enabled, but only one chunk at a time). That the ie ternary is still in the concurrency is simply because it was not removed when we also added the ternary for allowing chunking at all.
