### ISSUE TITLE
Problems with thumbnails generation after deleting items

### ISSUE THREAD

**Issue by micmicovich** [FineUploader/fine-uploader#1419] opened 2015-06-05 13:52 UTC
1. Drop dozen images
2. Delete one before thumbnail generation finished for all items.
   At this step in IE and Firefox thumbnail generation stops for some items.
2. Continue deleting and delete all items
3. Drop that images again - no thumbnail is generated

Checked in:
Firefox 38.0.5
Chrome 43.0.2357.81 m
Opera 29.0.1795.60
IE 10.0.9200.16866

with Fine Uploader 5.2.1

**Comment by rnicholus** [comment] 2015-06-05 13:58
Likely a duplicate of #1416. If you are still seeing the issue in 5.2.2, I'll re-open.

**Comment by micmicovich** [comment] 2015-06-05 14:07
The situations are different.
In https://github.com/FineUploader/fine-uploader/issues/1416 you exclude 
item that has not been uploaded.
In this issue you delete item that has been already uploaded.

**Comment by rnicholus** [comment] 2015-06-05 14:39
Are you able to reproduce this with the 5.2.2 version?

**Comment by micmicovich** [comment] 2015-06-05 14:44
At 
http://fineuploader.com/customize.html
I see "Download 5.2.1" button.

**Comment by rnicholus** [comment] 2015-06-05 14:46
Yes, 5.2.2 hasn't been released yet. Regardless, I was finally able to reproduce this in firefox using the 5.2.2 code. I'm looking into this further now.

**Comment by rnicholus** [comment] 2015-06-05 15:26
I'm able to reproduce in any browser, and the gallery template is not required as far as I can tell. Only a "preview" element in the template. 

This also uncovered another issue which is fairly minor but I will fix as well. An attempt is made to "update" the preview after a file has uploaded successfully, even if there is no thumbnailUrl in the response and client-side preview generation is possible.

**Comment by rnicholus** [comment] 2015-06-05 15:46
I think I have a fix for this. If you'd like to verify that I've fixed all of the issues you've reported in the last couple days (#1416, #1417, #1418, and #1419) before I release 5.2.2, I can get you the pre-release.

**Comment by micmicovich** [comment] 2015-06-08 08:03
Ok, I'm waiting for pre-release.

**Comment by rnicholus** [comment] 2015-06-08 12:01
S3, azure, or a custom endpoint you control?

**Comment by micmicovich** [comment] 2015-06-08 12:04
Custom endpoint

**Comment by rnicholus** [comment] 2015-06-08 13:41
http://releases.fineuploader.com/hotfix/5.2.2/fine-uploader-5.2.2.zip

**Comment by micmicovich** [comment] 2015-06-08 14:20
Looking into it now.

**Comment by rnicholus** [comment] 2015-06-08 21:37
I plan on releasing 5.2.2 tomorrow morning (Central Time) unless I hear that there are additional issues caused by these fixes. I didn't see any.

**Comment by micmicovich** [comment] 2015-06-09 05:54
There are additional issues. Please, wait  a little

**Comment by micmicovich** [comment] 2015-06-09 09:14
All issues (#1416, #1417, #1418, and #1419) - ок.

When I begun to test, I faced the problem, 
that later was hard to reproduce.
Problem: 
thumbnail generation stops at some item (more often closer to the end of list).
How to reproduce:
- Firefox 38.0.5
- a lot of open tabs (~30)
- number of images: 36
- image size: 1-2 Mb
- Fine Uploader element outside of form
- a little of system memory
- CPU: high loaded (not necessarily)

But if thumbnail was not generated for even one item,
after deleting all items and uploading them again, 
no thumbnail is generated.

**Comment by rnicholus** [comment] 2015-06-09 11:47
This does not sound like a new issue, nor does it sound like one that will
be easily reproduced. I'll see if I can reproduce, and if I am unable to do
so in a reasonable amount of time, I don't see this holding up the hotfix
release.

**Comment by rnicholus** [comment] 2015-06-09 11:58
Also you'll need to quantify "a little of system memory".

**Comment by micmicovich** [comment] 2015-06-09 12:44
I've edited the post: "a little of FREE system memory"
~350 Mb on Windows 7 Ultimate

**Comment by rnicholus** [comment] 2015-06-09 12:50
Please move all of this to a new case

**Closed** 2015-06-09 16:02 UTC
Labels: 5 - Done, bug, to fix, UI
