### ISSUE TITLE
Empty file check validation is broken

### ISSUE THREAD

**Issue by glopz** [FineUploader/fine-uploader#1381] opened 2015-03-10 07:19 UTC
there seems to be a bug when selecting a 0byte file, it always return a -1 byte size which obviously fails the emptyError check in uploader.basic.api.js at line 1738

**Comment by rnicholus** [comment] 2015-03-10 14:19
Thanks for reporting this. Looks like a regression, created in 5.0.0 during work on #937, which was a major refactor of the library. This one slipped through. The bug was introduced in 05a25f9b2881a6a2631e7bde6661859e554ca75, and the bug appears to be caused by [an improper evaluation of the file size in the upload-data module](https://github.com/FineUploader/fine-uploader/blob/5.0.0/client/js/upload-data.js#L79). We'll fix this as part of 5.2.0.

**Comment by rnicholus** [comment] 2015-03-30 21:19
Fixed in 5.2.0-21

**Closed** 2015-04-16 14:50 UTC
Labels: 5 - Done, bug, regression, to fix
