### ISSUE TITLE
Manual upload stops prematurely when lot of files are uploaded

### ISSUE THREAD

**Issue by mohitjee15** [FineUploader/fine-uploader#1439] opened 2015-07-23 10:42 UTC
In the demo page :- http://fineuploader.com/demos

I tried to upload near about 1800 files all pretty small less than 1 MB.

Once I click on Upload button it started uploading, but after 840 files the progress bar disappears and for the rest of the 760 files I have to click "Upload" button again.

We are also facing similar problem in our end.

**Comment by rnicholus** [comment] 2015-07-23 12:47
Which browsers are you using to reproduce this? If I'm able to reproduce
myself, I'll look into a fix for 5.3.0.

**Comment by rnicholus** [comment] 2015-07-23 17:37
It's tough to reproduce something that requires 1800 files to be uploaded. I'm not seeing any issues in the develop branch. There were a couple potentially related issues fixed there, and they will be part of 5.3.0. Please let me know if the 5.3.0-8 build fixes your issue.

**Comment by mohitjee15** [comment] 2015-07-24 02:14
Chrome browser. Version 42 i think.
Which browsers are you using to reproduce this? If I'm able to reproduce
myself, I'll look into a fix for 5.3.0.
On Thu, Jul 23, 2015 at 5:42 AM Mohit Suman <notifications@github.com>
wrote:

> In the demo page :- http://fineuploader.com/demos
>
> I tried to upload near about 1800 files all pretty small less than 1 MB.
>
> Once I click on Upload button it started uploading, but after 840 files
> the progress bar disappears and for the rest of the 760 files I have to
> click "Upload" button again.
>
> We are also facing similar problem in our end.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FineUploader/fine-uploader/issues/1439>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/FineUploader/fine-uploader/issues/1439#issuecomment-124084105>
.

**Comment by mohitjee15** [comment] 2015-07-24 12:07
When are you guys releasing `5.3.0` as it is in `dev` branch? Because till then it is a production bug for us.

One more thing what problems are you facing in uploading 1800 files?
We just copy pasted a bunch of files and were able to test it 5 mins.

**Comment by rnicholus** [comment] 2015-07-24 12:48
5.3.0 is in develop. The latest build is 5.3.0-8. For information on how to
download the latest dev build of your choice, see my comment at
https://github.com/FineUploader/fine-uploader/issues/1432#issuecomment-118995654

**Comment by rnicholus** [comment] 2015-07-24 18:05
5.3.0 will likely be released in the next week or two. In the meantime, you will want to ensure your issue is fixed in the pre-release before we actually release.

**Comment by rnicholus** [comment] 2015-07-29 16:04
Everything is looking fine on my end on develop. Closing for now. I can re-open if you're able to reproduce on develop and have more specifics reguarding reproduction.

**Comment by rnicholus** [comment] 2015-07-29 17:55
After a few more attempts, I am now able to reproduce, though only after about 2700+ files.

**Comment by rnicholus** [comment] 2015-07-29 18:43
After further investigation, the issue occurs when a very large number of files is submitted and the `uploadStoredFiles` method is called before Fine Uploader has finished verifying all the files submitted files. The files are only eligible for upload after various internal checks are run during a processing phase for each file that is submitted. 

When `uploadStoredFiles` is called, it simply loops over an internal array of verified files and submits them to the upload controller to be queued or uploaded. When the issue described here occurs, this internal array does not yet contain all submitted files as not all submitted files have been verified. This also explains why calling `uploadStoredFiles` again later uploads the remaining files.

I think a reasonable solution may be to check if any files are still in the `qq.status.SUBMITTING` state once we finish iterating over the array of verified "stored" files to upload. If there are any files in this state, then we probably want to wait a bit and attempt to process items in the stored files array again.

**Comment by rnicholus** [comment] 2015-07-29 18:58
This is now fixed in the develop branch. Please verify on your end before release @mohitjee15.

Pre-release build number incremented to  "-9" in b7053e5b2dc56bdc2e803936c1856e8d0cd1765e.

**Comment by rnicholus** [comment] 2015-07-29 20:17
I just pushed the release candidate to npm: "fine-uploader@5.3.0-11".

**Comment by mohitjee15** [comment] 2015-07-31 04:59
ok i'll verify today and let you know.

**Comment by mohitjee15** [comment] 2015-08-03 11:07
Ok verified in chrome version 42, it works fine. My colleague checked it out @https://github.com/arpit2438735/

**Comment by rnicholus** [comment] 2015-08-03 12:48
Thanks for the update. Looks like we're ready to release 5.3.0.

**Closed** 2015-08-03 20:02 UTC
Labels: 5 - Done, bug, to fix
