### ISSUE TITLE
function as delete endpoint

### ISSUE THREAD

**Issue by buganini** [FineUploader/fine-uploader#1876] opened 2017-07-04 21:59 UTC
## Type of issue
- [ ] Bug report
- [x] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

#### Feature request details 
To postpone deleting action until being submitted with a form, it's useful if endpoint can be a function, or just do nothing if endpoint is null, then do local deleting logic in callbacks.onDelete.

**Comment by rnicholus** [comment] 2017-07-05 04:18
duplicate of #1320

**Closed by rnicholus** 2017-07-05 04:18 UTC
