### ISSUE TITLE
Once a file is retried, TotalProgress is not updated.

### ISSUE THREAD

**Issue by mohitjee15** [FineUploader/fine-uploader#1424] opened 2015-06-11 06:50 UTC
If you update one or more files, the total progress is not updated.
Say you uploaded 3 files of 100 MB each, and 1 one of them failed.
Next time when you click on retry of the failed file.
The total Progress says 200mb instead of 300mb.

When we checked the code for the fine uploader library, there was no callback inside onStatusChange function to update the totalProgress incase the status changes to qq.status.UPLOAD_RETRYING.

Doing this fixed the problem for us

previous:
```javascript
onStatusChange: function(id, oldStatus, newStatus) {
            if (newStatus === qq.status.CANCELED || newStatus === qq.status.REJECTED) {
                onCancel(id);
            }
            else if (newStatus === qq.status.SUBMITTING) {
                onNew(id);
            }
        },
```

new:

```javascript
onStatusChange: function(id, oldStatus, newStatus) {
            if (newStatus === qq.status.CANCELED || newStatus === qq.status.REJECTED) {
                onCancel(id);
			} else if ((newStatus === qq.status.SUBMITTING) || (newStatus === qq.status.UPLOAD_RETRYING)) {
                onNew(id);
            }
        },
```

if you want I can send a pull request?

**Comment by rnicholus** [comment] 2015-06-11 14:03
Sorry, I'm not seeing an issue. You'll have to be much more specific about the conditions needed to reproduce, and the _specific_ issue you are seeing.

**Comment by mohitjee15** [comment] 2015-06-12 05:32
We are on the latest version 5.2.2.

In the totalProgress callback http://docs.fineuploader.com/api/events.html#totalProgress,

We are getting two things totalUploadedBytes and totalBytes.

So in the following scenario we are getting correct values for totalUploadedBytes and totalBytes:-
- When new files are added
- When a file is deleted
- When a file fails

But we get incorrect value for totalBytes in the following scenario:-

**Preconditions:-**

- We are using fine uploader core
- We are trigger the uploads manually
- We are doing manual retry (autoRetry is disabled)

**Scenario:-**

1) We queued 4 files for upload, foo.pdf(50MB), bar.pdf(50MB), foobar.pdf(50MB), barfoo.pdf(50MB).
2) We triggered the upload using uploader.uploadStoredFiles().
3) Say foo.pdf, bar.pdf failed and foobar.pdf and barfoo.pdf passed.
4) Now if we retry foo.pdf and bar.pdf simultaneously, in the callback for totalBytes we should receive  100MB (50MB for foo.pdf and 50 MB for bar.pdf) but it shows 50MB only.

**Comment by rnicholus** [comment] 2015-06-12 13:04
Thanks. We will look into this further.

**Comment by rnicholus** [comment] 2015-06-18 20:11
Can you elaborate on how you are retrying two files "simultaneously"? I'm not seeing how this is even possible with the current API. Brief testing shows the total bytes being updated correctly when the second file is retried.

**Comment by mohitjee15** [comment] 2015-06-19 06:23
What i meant with "simultaneously" is while the first retried file is in
progress, if you retry the second one also.

On Fri, Jun 19, 2015 at 1:42 AM, Ray Nicholus <notifications@github.com>
wrote:

> Can you elaborate on how you are retrying two files "simultaneously"? I'm
> not seeing how this is even possible with the current API. Brief testing
> shows the total bytes being updated correctly when the second file is
> retried.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FineUploader/fine-uploader/issues/1424#issuecomment-113276074>
> .
>



-- 
Mohit Suman
Web Developer(JS Ninja)

**Comment by rnicholus** [comment] 2015-06-19 13:36
As you can see from my post, I am still unable to reproduce this. If you are confident an issue exists, please share the exact line or lines that are causing the issue, along with a proposed fix.

**Comment by rnicholus** [comment] 2015-06-23 14:38
Closing as I am unable to reproduce. I'd be happy to consider re-opening if this changes.

**Closed by rnicholus** 2015-06-23 14:39 UTC
Labels: waiting for feedback

**Comment by mohitjee15** [comment] 2015-06-23 14:51
*"As you can see from my post, I am still unable to reproduce this. If you
are confident an issue exists, please share the exact line or lines that
are causing the issue, along with a proposed fix."*

Sorry for not replying early.

But in my first post itself I have mentioned the line that has the problem
and the fix that is required.

I'll be happy to share create a pull request if you want.

On Tue, Jun 23, 2015 at 8:09 PM, Ray Nicholus <notifications@github.com>
wrote:

> Closing as I am unable to reproduce. I'd be happy to consider re-opening
> if this changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FineUploader/fine-uploader/issues/1424#issuecomment-114529321>
> .
>



-- 
Mohit Suman
Web Developer(JS Ninja)
