### ISSUE TITLE
Add configuration option for removing mandatory json {success: true} from traditional endpoint upload

### ISSUE THREAD

**Issue by zmilan** [FineUploader/fine-uploader#1445] opened 2015-07-30 16:45 UTC
Based on previous (conversation)[https://github.com/FineUploader/fine-uploader/issues/1025#issuecomment-126341926), add configuration option to remove mandatory json response with {success: true} for traditional endpoint response, so we can go just with HTTP 201 response like success.

**Comment by rnicholus** [comment] 2015-07-30 21:13
Note that we will still need to require IE9 & IE8 to return a 200 response with `{"success":true}` due to issues with handling of non-200 responses in those browsers when an iframe is involved.

I don't want to make this a configuration option. Instead, 6.0 would mandate that endpoints declare the status of the upload request via the response status code, unless the request comes from IE9/IE8. All of this becomes a bit more complicated in a cross-origin environment. 

Honestly, I don't expect to to implement this given the scope of the change and the potential edge cases that may suffer.

**Comment by zmilan** [comment] 2015-07-31 05:56
Ok, I understand this. In our specific case IE9&IE8 are not important, so we have much simpler case. Thanks for accept this.

**Comment by rnicholus** [comment] 2015-08-05 15:36
Duplicate of #1325.

**Closed by rnicholus** 2015-08-05 15:36 UTC
Labels: 0 - Discuss, breaking change, enhancement, MAY BE KILLED
