### ISSUE TITLE
Make fineuploader compatible with browserify

### ISSUE THREAD

**Issue by sjelfull** [FineUploader/fine-uploader#1299] opened 2014-09-28 19:09 UTC
I would love to pull in fineuploader like any other module in my projects, through browserify.

Is that possible now, or could you make it happen?

**Comment by max-mykhailenko** [comment] 2015-02-25 10:48
+1

**Comment by rnicholus** [comment] 2015-10-11 03:54
duplicate of #789

**Closed by rnicholus** 2015-10-11 03:54 UTC
Labels: 0 - Discuss, enhancement
