### ISSUE TITLE
Only one of multiple checkbox values is submitted with form support

### ISSUE THREAD

**Issue by mkucej** [FineUploader/fine-uploader#1823] opened 2017-04-18 19:02 UTC
## Type of issue
- [x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.14.1

#### Browsers where the bug is reproducible
Firefox

#### Operating systems where the bug is reproducible
Ubuntu 14.04

#### Exact steps required to reproduce the issue
1. Use form support, `FineUploaderBasic()`
2. Add two or more checkboxes with name `foo[]`
3. Only last checkbox value is submitted.

#### All relevant Fine Uploader-related code that you have written
```Javascript
        var uploader = new qq.FineUploaderBasic({
            form: {
                element: document.getElementById('form'),
                autoUpload: false
            }
        });
        $('#form').on('click', ':submit', function(e) {
            e.preventDefault();
            uploader.addFiles([$('#form input:file')[0]]);
            uploader.uploadStoredFiles();
        });
```

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
no template, just a form

#### Detailed explanation of the problem
Only last checkbox value is submitted, if one checks multiple checkboxes. Relevant code seems to be here:

https://github.com/FineUploader/fine-uploader/blob/24ed927e890331b6c4cbe39e926be2ae81ad30e3/client/js/form-support.js#L152
</details>

**Comment by rnicholus** [comment] 2017-04-19 00:54
duplicate of #1577

**Closed by rnicholus** 2017-04-19 00:54 UTC
