### ISSUE TITLE
Create Changelog

### ISSUE THREAD

**Issue by feltnerm** [FineUploader/fine-uploader#1280] opened 2014-09-08 15:05 UTC
Proposing that Fine Uploader begins to use a changelog for new releases. Since we are using the angular JS commit conventions, we can theoretically automatically generate this. We can either continue to update the blog with more user-friendly-worded changes, or just use a CHANGELOG in the repo.

**Comment by rnicholus** [comment] 2015-11-05 23:05
duplicate of #1294

**Closed by rnicholus** 2015-11-05 23:05 UTC
Labels: 2 - Do, documentation, technical debt
