### ISSUE TITLE
Invalid Date in `x-amz-date` Header for S3 Uploads

### ISSUE THREAD

**Issue by feltnerm** [FineUploader/fine-uploader#1535] opened 2016-03-01 21:28 UTC
## Type of issue
bug

## Uploader type
S3

### Fine Uploader version
5.5.1

### Browsers where the bug is reproducible
IE11, Safari 9

### Operating systems where the bug is reproducible
Windows + OS X

### Exact steps required to reproduce the issue
1. Upload file

### All of your Fine Uploader initialization JavaScript code
Defaults.

### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
Defaults.

### Detailed explanation of the problem

#1387 added ability to account for user's clock drift by adjusting the `x-amz-date` header based on the `options.signatureSpec.drift` value via `new Date(Date.now() + options.signatureSpec.drift)` [1]. 

`Date.now() + options.signatureSpec.drift` in IE11 and Safari returns a string with `options.signatureSpec.drift` concatenated on to it rather than an incremented datetime (I have no idea why; note that in Chrome 50 this appears to actually add milliseconds to the time which seems more correct). This means the `x-amz-date` header is the string value `"Invalid Date"` rather than an actual valid date, and we end up seeing the following logs before the upload finally fails:

```
[Fine Uploader 5.5.0] POST request for 1 has failed - response code 403
[Fine Uploader 5.5.0] Specific problem detected initiating multipart upload request for 1: 'AWS authentication requires a valid Date or x-amz-date header'.
```

1 - https://github.com/FineUploader/fine-uploader/blob/master/client/js/s3/request-signer.js#L570

**Comment by rnicholus** [comment] 2016-03-02 16:00
I'm not seeing an issue in IE11 or Safari 9 locally. Any idea how this can be reliably reproduced?

**Comment by rnicholus** [comment] 2016-03-02 16:14
After looking into the web application that is experiencing this issue, I have determined that this is caused by that app overriding `Date.now` with another function, specifically `Date.now = function() {return new Date()}`. So, closing as this is not a Fine Uploader issue.

**Closed by rnicholus** 2016-03-02 16:14 UTC
