### ISSUE TITLE
stopOnFirstInvalidFile doesn't works

### ISSUE THREAD

**Issue by fundup** [FineUploader/fine-uploader#1545] opened 2016-03-16 11:25 UTC
## Type of issue [REQUIRED]
 "bug"

## Uploader type [REQUIRED]
"S3"

## Bug details 
stopOnFirstInvalidFile option on validation seems to have trouble. When an image doesn't respect sizeLimit other image are not uploaded.

here is my config: 

```
validation: {
                    allowedExtensions: ['jpeg', 'jpg', 'png'],
                    acceptFiles: "image/gif, image/jpeg, image/png",
                    sizeLimit: 20000000, // 20MB
                        minHeight: 1000, //1000px
                        minWidth: 1000
                    },
                    stopOnFirstInvalidFile: false
                }
```
### Fine Uploader version [REQUIRED]
5.5.0

### Browsers where the bug is reproducible [REQUIRED]
Chrome

### Operating systems where the bug is reproducible [REQUIRED]
Ubuntu 14.04

### Exact steps required to reproduce the issue [REQUIRED]
For example:
1. Select 5 image with one which does not respect
2. first images will upload not  others

Thanks

**Comment by rnicholus** [comment] 2016-03-16 13:51
As it stands, your configuration options are not valid, in fact, the JavaScript posted in your code block above is not valid either (extra closing bracket). This is likely the source of your issue as I am not able to reproduce myself given your steps. Please see the `validation` option on the documentation site for information on how to properly structure this option.

**Closed by rnicholus** 2016-03-16 13:51 UTC

**Comment by fundup** [comment] 2016-03-18 09:35
Posted code is wrong due to I deleted a comant and image: {  line at the same time :( . So my option is structure properly I think.
```
validation: {
                    allowedExtensions: ['jpeg', 'jpg', 'png'],
                    acceptFiles: "image/gif, image/jpeg, image/png",
                    sizeLimit: 20000000, // 20MB : Attention limit must match with php
                    image: {
                        minHeight: 1000, //1000px
                        minWidth: 1000
                    },
                    stopOnFirstInvalidFile: false
                },
```
I will try to find a solution and I'll post it.

**Comment by rnicholus** [comment] 2016-03-18 14:48
I wasn't able to reproduce using your code, or even the modified code with the correct options set. The validation logic worked as expected. What version of Fine Uploader are you using?
