### ISSUE TITLE
S3 bucket undefined for file ID 0?

### ISSUE THREAD

**Issue by jasonm** [FineUploader/fine-uploader#1365] opened 2015-02-12 19:32 UTC
I recently upgraded from FineUploader 5.0.5 to 5.1.3.  Requests to my server to delete S3 files used to contain a `bucket` param, but that param now is delivered as `undefined`:

![transcripts___minerva_schools-2](https://cloud.githubusercontent.com/assets/1031/6175267/0c289ed0-b2aa-11e4-9014-800b5efe0e87.png)

I'm not familiar with the FineUploader internals, but it appears that `this.getBucket` inspects `this._cannedBuckets` and `this._buckets` which are empty, but the 5.0.5 implementation called `qq.s3.util.getBucket(this.getEndpoint(id))` which worked due to an endpoint being configured:

![screen shot 2015-02-12 at 11 28 09 am](https://cloud.githubusercontent.com/assets/1031/6175307/654ede66-b2aa-11e4-970f-a6542fe87dbd.png)

Am I configuring FineUploader incorrectly for 5.1.3?

Would additional config/options be helpful to troubleshoot?

**Comment by rnicholus** [comment] 2015-02-12 19:45
I'm not seeing the issue on our live S3 demo at fineuploader.com, which is also using 5.1.3.  Please show your fine-uploader related JS code.

**Comment by jasonm** [comment] 2015-02-12 23:31
Thanks @rnicholus - relevant JS is https://gist.github.com/jasonm/06371654d172f84f87aa and full page source https://gist.github.com/jasonm/c33596d685c05efcdfeb

URL is https://minerva.kgi.edu/application/application-center/ but that's behind a signup flow.

**Comment by rnicholus** [comment] 2015-02-12 23:33
What is your request endpoint?

**Comment by jasonm** [comment] 2015-02-13 19:11
Hi @rnicholus, the `requestEndpoint` value is https://s3.amazonaws.com/minervaschools-application-upload declared on https://s3.amazonaws.com/minervaschools-application-upload

**Comment by rnicholus** [comment] 2015-02-13 19:19
Something is missing from your example code.  You are pulling in v5.0.5, not 5.1.3.  The demo on our site is working as expected, so I have to assume that there is some issue specific to your setup.  I'm also unable to reproduce locally.  

If you provide a link to a live site where this can be easily reproduced (with non-minified code) I can take a closer look.

**Comment by rnicholus** [comment] 2015-02-19 20:26
Closing as not reproducible.  If you can provide a live example where this is reproducible, I will be happy to re-open.

**Closed by rnicholus** 2015-02-19 20:26 UTC
Labels: waiting for feedback
