### ISSUE TITLE
Drag n Drop not working in Edge Browser

### ISSUE THREAD

**Issue by Manidipa** [FineUploader/fine-uploader#1547] opened 2016-03-21 08:13 UTC
Hi Ray 

Drag n Drop is not working in Edge browser win 10 system latest version. As Microsoft  Drag n Drop is supported

http://mspoweruser.com/windows-10-build-10565-microsoft-edge-gets-support-for-file-drag-and-drop-tab-previews-and-more/

Please help us on that in case of any change in FineUploader. We are using FineUploader for both S3(5.1.3) and also wthout S3 (5.0.4)

Please let us know in case of any change in the code so that it can detect the edge browser.

Thanks in advance for your help

Regards
Manidipa

**Comment by rnicholus** [comment] 2016-03-21 12:43
Duplicate of #1422.

**Closed by rnicholus** 2016-03-21 12:43 UTC

**Comment by rnicholus** [comment] 2016-04-20 16:59
Please see https://github.com/FineUploader/fine-uploader/issues/1422#issuecomment-212513830.
