### ISSUE TITLE
Error when attempting to parse xhr response text when uploading large chunked files

### ISSUE THREAD

**Issue by bradwestness** [FineUploader/fine-uploader#1558] opened 2016-04-22 03:14 UTC
## Type of issue
Bug

## Uploader type
Traditional

### Fine Uploader version
5.3.2 through 5.6.0

### Browsers where the bug is reproducible
Firefox and Google Chrome

### Operating systems where the bug is reproducible
Windows 8.1, Windows 10

### Exact steps required to reproduce the issue
For example:
1. Upload a large file (not sure the exact threshold, but > 8 MB will cause the issue)
2. Attempt to access the `xhr` or `response` variables in the onComplete callback method

### All of your Fine Uploader initialization JavaScript code

            var fineUploader = new qq.FineUploader({
                element: document.getElementById(config.elementId),
                template: config.template,
                request: {
                    endpoint: '/IncrementalFileUpload',
                    params: {
                        'destinationDirectory': config.destinationDirectory
                    }
                },
                //retry: {
                //    enableAuto: true
                //},
                chunking: {
                    enabled: true,
                    concurrent: {
                        enabled: true
                    }
                    //success: {
                    //    endpoint: "/FileUploadComplete"
                    //}
                },
                multiple: config.allowMultiple,
                callbacks: {
                    onSubmit: function(id, name) {
                        config.onSubmitCallback(name);

                        //var getMd5Promise = new qq.Promise();
                        //calculateMd5(id, getMd5Promise);
                        //return getMd5Promise;
                    },
                    onComplete: function(id, name, response, xhr) {
                        var success = response && !!response.success,
                            uuid = fineUploader.getUuid(id);

                        if (success) {
                            $("[qq-file-id='" + id + "'] .fu-upload-success-selector").removeClass("fu-hide");
                        } else {
                            $("[qq-file-id='" + id + "'] .fu-upload-fail-selector").removeClass("fu-hide");
                        }

                        config.onCompleteCallback(name, success, uuid);
                    }
                },
                validation: {
                    allowedExtensions: config.allowedExtensions
                },
                classes: {
                    //http://docs.fineuploader.com/branch/master/features/styling.html
                    dropActive: "fu-upload-drop-area-active",
                    success: "fu-upload-status-success",
                    fail: "fu-upload-status-fail",
                    hide: "fu-hide"
                },
                formatFileName: function (rawFileName) {
                    return rawFileName;
                }
            });

### Detailed explanation of the problem
When a large file is uploaded using chunking in Google Chrome and Mozilla Firefox, the final chunk causes an exception when attempting to parse the XHR response text:
![image](https://cloud.githubusercontent.com/assets/1802434/14730538/1db0c6a0-080d-11e6-9dba-9f7fa2c9c2b2.png)

It seems that the XHR object is not initialized during this method for some reason, and it will also be undefined in the onComplete callback function.
![image](https://cloud.githubusercontent.com/assets/1802434/14730544/3175d1c6-080d-11e6-9d90-206134413bc7.png)

Strangely, the response object is also missing properties when this occurs despite their presence in the actual response JSON.
![image](https://cloud.githubusercontent.com/assets/1802434/14730640/165b214c-080e-11e6-8a45-8e6e23b9032f.png)

![image](https://cloud.githubusercontent.com/assets/1802434/14730645/1d0308fc-080e-11e6-8962-932e707890ee.png)

**Comment by rnicholus** [comment] 2016-04-22 03:34
Hmm, what you're describing here is a very serious issue that likely _should_ affect a large number of users. But this is the first such report I've seen. I would be surprised if the issue was entirely with Fine Uploader and not something specific to your environment or more likely an issue with your server response. Perhaps some other JavaScript on the page is conflicting with Fine Uploader, or your server is returning an especially odd response that is causing an unexpected issue with response parsing. I'm not seeing this issue myself locally, so if you'd like me to look closer to rule out any specific issue with Fine Uploader, providing me with a link to a site where you are able to reproduce this will be most helpful. It will also help if you either provide a sourcemap for any minified code, or perhaps just switch all of your minified code for non-minified versions for easier debugging.

**Comment by rnicholus** [comment] 2016-04-22 03:34
BTW I see you're from UW. Fine Uploader is developed and maintained right here in Madison!

**Comment by bradwestness** [comment] 2016-04-22 03:42
Cool! I am now at a private company that operates out of Beloit, but I was in Madison until November of last year. :)

We were definitely not having this issue until a few weeks ago either, and nothing has changed with our implementation, so my thought is it might only occur on the most recent version(s) of Chrome/Firefox. It also doesn't occur on Internet Explorer or Edge. My first instinct was to verify that the JSON we were returning was valid, but every response from our incremental file handler is identical to the one in the screenshot above, so I don't know why it would occur only on the .finalizeChunks call (and there's no "status" parameter in the response JSON to begin with).

**Comment by rnicholus** [comment] 2016-04-22 03:46
I did just attempt to reproduce in the latest version of Chrome (it's my primary development browser). Can you direct me to one of your applications where you have been able to reproduce this? If you are apprehensive about posting a link in public, I'd be happy to provide you with an email address or a twitter account to receive this link. This will definitely be the easiest way to get to the bottom of this issue.

**Comment by bradwestness** [comment] 2016-04-22 03:47
Some contact info to receive a link would be good. I'll have to talk to my team about getting some credentials for you since all of our usages are behind authentication.

**Comment by rnicholus** [comment] 2016-04-22 03:48
You can send this information to ray@fineuploader.com.

**Comment by bradwestness** [comment] 2016-04-22 14:48
Here's a sample ASP.NET project that should enable you to re-create the issue: https://onedrive.live.com/redir?resid=33C6ADC7636F5E0A!1039811&authkey=!AD_cqZ4FGdYBWOs&ithint=file%2czip

**Comment by rnicholus** [comment] 2016-04-22 14:51
I'm afraid I don't have any way to run an ASP.NET project.

**Comment by bradwestness** [comment] 2016-04-22 15:22
Alright, her'es a PHP version! :)

[fineuploader-test.zip](https://github.com/FineUploader/fine-uploader/files/232088/fineuploader-test.zip)

**Comment by rnicholus** [comment] 2016-04-22 15:38
I run a simple PHP server using your included PHP file, navigated to the index page, dropped a 30 MB file, and the upload completed successfully in the latest version of Chrome. The issue you are seeing is almost definitely a result of something specific in your particular environment. With this being fairly clear and me being unfortunately unable to reproduce your error, I'm going to close this case, but would certainly consider re-opening if you are able to provide a sure way to reproduce your issue.

**Closed by rnicholus** 2016-04-22 15:38 UTC
Labels: waiting for feedback

**Comment by bradwestness** [comment] 2016-04-22 15:42
The upload does complete successfully, but I still get the error in my console when using that sample PHP app on a completely fresh XAMPP install with nothing except bootstrap and jQuery on the page.

**Comment by bradwestness** [comment] 2016-04-22 15:52
I just had a co-worker try the sample app on his Mac (on Chrome) and it got the same error, so that also rules out it being a Windows-only issue.

**Comment by rnicholus** [comment] 2016-04-22 16:07
The only errors I'm seeing are 404s for the success/loading/failure images. Everything is functioning as expected.

**Comment by ssineriz** [comment] 2017-06-12 07:43
I had exactly the same issue, and managed to fix it adding a check on the xhr variable passed in the finalizeChunk method (jquery.fine-uploader.js@3835)

```javascript
finalizeChunks: function(id, responseParser) {
	var lastChunkIdx = handler._getTotalChunks(id) - 1, xhr = handler._getXhr(id, lastChunkIdx);
	if (responseParser) {
		if (xhr == null) xhr = handler._getXhrs(id)[0]; // <- Added this row
		return new qq.Promise().success(responseParser(xhr), xhr);
	}
	return new qq.Promise().success({}, xhr);
}
```
I didn't go any further on the matter, but I guess that, for the last chunk, some still unfulfilled promise didn't populate the xhr when the finalize is called. All other previous chunks returned a non null xhr.

**Comment by gullevek** [comment] 2018-07-23 09:55
After updating to Firefox 61.0.1 on macOS the bug moves to a different area.

It works in Opera and Chrome, but not Safari (11.1.2) and FF (61.0.1)

I use the sample PHP backend (as described here: https://docs.fineuploader.com/quickstart/03-setting_up_server.html)

with the following frontend config:

```
	// Some options to pass to the uploader are discussed on the next page
	// var uploader = new qq.FineUploaderBasic({
	var uploader_1 = new qq.FineUploader({
		debug: true,
		element: $('fine-uploader-1'),
		request: {
			endpoint: "/fineUploader/vendor/fineuploader/php-traditional-server/endpoint.php"
		},
		deleteFile: {
			enabled: true,
			endpoint: "/fineUploader/vendor/fineuploader/php-traditional-server/endpoint.php"
		},
		chunking: {
			enabled: true,
			concurrent: {
				enabled: true
			},
			success: {
				endpoint: "/fineUploader/vendor/fineuploader/php-traditional-server/endpoint.php?done"
			}
		},
		resume: {
			enabled: true
		},
		retry: {
			enableAuto: true,
			showButton: true
		}
	});
```

When I look into the console log then there is no Response at all, compare to the response from chrome

> {"success":true,"uuid":"138da619-0726-4799-9f48-0c6a7774c642","uploadName":null}

**Comment by gullevek** [comment] 2018-07-24 02:57
I need to revise this as this seems to be a local network problem that has nothing to do with the script itself.
