### ISSUE TITLE
Drag n Drop support in Edge Browser

### ISSUE THREAD

**Issue by Manidipa** [FineUploader/fine-uploader#1442] opened 2015-07-28 13:49 UTC
Hi Ray
 
Drag n Drop of file is not supported in fine uploader control with windows 10 Edge browser. Do you have any fix for this .

thanks in advance for your support

manidipa

**Comment by rnicholus** [comment] 2015-07-28 14:08
Duplicate of #1422. Edge doesn't currently support dropping of files - not a Fine Uploader issue and there is no workaround. Please see 1422 for details.

**Closed by rnicholus** 2015-07-28 14:08 UTC

**Comment by Manidipa** [comment] 2016-03-21 07:27
Hi Ray
We are using win 10 licensed version 10.0.10586. As per Microsoft drag n drop is supported in edge browser but when try with fine uploder then it is not supported. 
 
http://mspoweruser.com/windows-10-build-10565-microsoft-edge-gets-support-for-file-drag-and-drop-tab-previews-and-more/

Please let us know what changes needed for this in fineuploader.

Regards
Manidipa

**Comment by rnicholus** [comment] 2016-04-20 16:59
Please see https://github.com/FineUploader/fine-uploader/issues/1422#issuecomment-212513830.
