### ISSUE TITLE
Initial/Canned files without extra request

### ISSUE THREAD

**Issue by thanosp** [FineUploader/fine-uploader#1361] opened 2015-02-07 06:43 UTC
As a developer I would like to provide an initial set of uploaded files without relying on sessions.

This is to be used when my form validation fails on server side.
I am not making an ajax request to submit the form and do not want to store data in sessions.
My form is rendered again with the same posted data in place, apart from the FineUploader part.

From the looks of it, I need something similar to `_addCannedFile` but public.
Is there a workaround possible?

**Comment by thanosp** [comment] 2015-02-07 06:47
Forgot to mention but possibly related to #1191. Maybe a public interface solves both.

**Comment by rnicholus** [comment] 2015-02-07 14:35
Yes, this seems to be a duplicate of the above mentioned case.

**Closed by rnicholus** 2015-02-07 14:35 UTC
