### ISSUE TITLE
Cors option expected still responses in No 'Access-Control-Allow-Origin' present

### ISSUE THREAD

**Issue by tychovbh** [FineUploader/fine-uploader#2045] opened 2018-08-22 18:25 UTC
## Type of issue
- [X] Bug report
- [ ] Feature request

## Uploader type
- [ ] Traditional
- [X] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Detailed explanation of the problem
I'm trying to upload a file. My application is in ReactJS so I need to validate the signature on a different domain. So I use the cors option to allow cross domain requests:
```js
cors: {
    //all requests are expected to be cross-domain requests
    expected: true,
},
```

with this enabled I still receive the following error:
Failed to load http://local.eyecons.com/vendor/fineuploader/php-s3-server/endpoint.php: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

Now I checked your demo page (https://fineuploader.com/demos.html#amazon-demo). And tried to upload a file, and I see the same error in console log: 
Failed to load https://s3-demo.fineuploader.com/s3demo-thumbnails-cors.php: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://fineuploader.com' is therefore not allowed access.

Is there a way to do this?
</details>

**Comment by rnicholus** [comment] 2018-08-22 21:46
The error you see in the demo has nothing to do with CORS - the aws account backing that demo is no longer functional. As for the issue you are seeing in your code, you’ll need to look closer at the response to see what the issue is. I can guarantee that the issue is on your server. And thus out of scope for this issue tracker.

**Closed by rnicholus** 2018-08-22 21:46 UTC
