### ISSUE TITLE
Thumbnail generation stops at some item 

### ISSUE THREAD

**Issue by micmicovich** [FineUploader/fine-uploader#1421] opened 2015-06-09 12:56 UTC
Thumbnail generation stops at some item (more often closer to the end of list).
How to reproduce:
- Firefox 38.0.5
- a lot of open tabs (~30)
- number of images: 36
- image size: 1-2 Mb
- Fine Uploader element outside of form
- a little of free system memory (~350 Mb on Windows 7 Ultimate)
- CPU: high loaded (not necessarily)

But if thumbnail was not generated for even one item,
after deleting all items and uploading them again,
no thumbnail is generated.

**Comment by rnicholus** [comment] 2015-06-09 13:59
I was unable to reproduce after a few rounds of testing. We'll keep an eye on this and, if we see it, are able to reasonably reproduce it, and are concerned that this is not an extreme edge case, we will investigate further in a future release.

**Comment by micmicovich** [comment] 2015-06-09 14:05
Ok, thank you.

**Comment by rnicholus** [comment] 2015-06-23 14:39
Closing as I am still unable to reproduce. We can consider re-opening if the situation changes.

**Closed by rnicholus** 2015-06-23 14:39 UTC
Labels: 0 - Discuss, bug, waiting for feedback
