### ISSUE TITLE
Odd behaviour when trying to remove an image in gallery mode 

### ISSUE THREAD

**Issue by micmicovich** [FineUploader/fine-uploader#1417] opened 2015-06-04 12:29 UTC
For
Chrome 43.0.2357.81 m
Opera 29.0.1795.60

Two cases:
when Fine Uploader element is placed
1.  outside of form
	No request is sent after trash button has been clicked
2.  inside form
	The behaviour is as if you have clicked submit button

In Firefox 38.0.5 and IE 10.0.9200.16866 - OK

**Comment by rnicholus** [comment] 2015-06-04 12:38
Most likely due to the close button lacking a `type="button"`. Adding that should fix the 2nd issue. Not sure what is causing the first issue for you. You'll have to show your code.

**Comment by rnicholus** [comment] 2015-06-04 13:50
Issue 2 will be addressed by updating the default templates to include `type="button"` on all `<button`>s in the upcoming hotfix release. I'm unable to reproduce the first issue though, so without your code and some ability to reproduce it, I will be unable to look into it any further.

**Comment by rnicholus** [comment] 2015-06-04 18:38
Working on this now as part of 5.2.2. After the second issue in the report is addressed, 5.2.2 will be pushed out as a hotfix release.

**Comment by rnicholus** [comment] 2015-06-04 19:13
I'm unable to reproduce either issue. Please provide your code, a list of steps required to reproduce, and the _specific_ issue(s) you are seeing.

**Comment by rnicholus** [comment] 2015-06-04 19:17
Nevermind, I able to reproduce by uploading a file and then clicking the delete icon. I mistakenly thought you were removing images with `autoUpload` set to `false` before triggering the upload process.

**Comment by micmicovich** [comment] 2015-06-05 11:58
Sorry, there was no opportunity to answer immediately.
I can reproduce described behaviour only with 
fine-uploader.js (5.1.3)
fine-uploader-gallery.css (5.2.1)

Do you need any sources now?

**Comment by rnicholus** [comment] 2015-06-05 12:17
Are you saying that you are using the 5.1 version of the JavaScript file with a gallery template and the 5.2 version of the CSS file? If so, that is completely unsupported and you likely will have issues. The gallery view requires you use at least v5.2 of the JS file, since it wasn't introduced until 5.2.

**Comment by rnicholus** [comment] 2015-06-05 12:21
...more specific to your case, one of the changes in 5.2 included an adjustment to th click handler code, which was needed for the gallery view. That might explain your first issue. As a matter of course, the JS and CSS/template files should be of the same version.

**Comment by micmicovich** [comment] 2015-06-05 12:29
Such ood configuration came out after some experements.
And I noticed that only when creted new clear test project
to reproduce described behaviour.

**Comment by rnicholus** [comment] 2015-06-05 12:52
Ok. So the first issue is expected, and should be resolved by using all 5.2 components in your project. All other issues you filed should be fixed in the hotfix/5.2.2 branch and will be released in the very near future, possibly today or Monday.

**Closed** 2015-06-09 16:02 UTC
Labels: 5 - Done, bug, documentation, to fix, UI
