### ISSUE TITLE
Demo s3 Uploader wont upload files larger than 6 meg in ie8

### ISSUE THREAD

**Issue by joebtron** [FineUploader/fine-uploader#1393] opened 2015-03-26 10:48 UTC
Hello, this is a continuation of this ticket which you closed https://github.com/FineUploader/integration-examples/issues/2

When uploading the 10.7mb file c:/windows/system32/ieframe.dll to http://fineuploader.com/demos.html#amazon-demo in a Windows 7 Virtualbox VM running IE8 the upload never finishes, the green window progress bar fills up. I've also tried an 8.9 mb file and after 20mins got a red upload failed notification, clearing the cache everytime, a 1.9 mb file was fine. As far as I can see, this behavior is common to all files over 6 MB as I also tried a 6.9mb mp4 file after that on the same page load which never finished uploading after around 20 mins. It seems to try to go to the page http://fineuploader.com/server/success.html?bucket=upload.fineuploader.com&key=.... and never finishes loading.

**Comment by rnicholus** [comment] 2015-03-26 11:42
The issue is with your vm or your environment. As I mentioned in the other case, I am able to upload a 10mb file to s3 on the demo page via a fresh ie8 vm without issue.

**Comment by rnicholus** [comment] 2015-03-26 11:51
Also, the success url you are listing is a static html file. If that is not loading quickly and the upload of such a small file is taking 20 mins, then most likely your vm network configuration needs some tweaking. I'm sorry, but that sort of support is far out of scope for this issue tracker.

**Closed by rnicholus** 2015-03-26 11:51 UTC
