### ISSUE TITLE
FineUploader crashes Google Chrome if you try uploading a very large file

### ISSUE THREAD

**Issue by jdq22** [FineUploader/fine-uploader#1399] opened 2015-04-22 02:51 UTC
I was uploading a 180GB file with the extension sparsebundle. Once I clicked OK to add the file to the uploader, the page stopped responding, and the UI never reflected the file being added. So if you close out the page and try loading any other page, you get the message on the bottom left, "Waiting for AppCache." No page will load until you force quit out of Google Chrome. I did this multiple times with the same results.

If you're on a Mac, you'll notice a large partial file in the following path: /private/var/folders/lp/d1dvvt713x78m12x266fvmsr0000gn/T/com.google.Chrome/zip_cache.

Once you delete the partial file, the browser returns to normal.

**Comment by rnicholus** [comment] 2015-04-22 02:56
Fine Uploader doesn't utilize AppCache. I just uploaded several 200+ MB files without issue in Chrome myself, so if there is a Fine Uploader specific issue here, it must have something to do with this specific file type. I'm not familiar with a "sparsebundle". Perhaps this is actually a folder disguised as a file? What happens if you attempt to upload this same file in other browsers? What about other sparsebundles or other large files in Chrome?

**Comment by teckno101** [comment] 2015-04-22 02:57
It's definitely not a Chrome only issue because I experienced a similar problem in Safari. A sparse bundle/image is exactly what you said it is, a folder disguised as a file. It's basically a DMG that can expand as you put files in it.

**Comment by rnicholus** [comment] 2015-04-22 02:58
If this is truly a folder instead of a file, then you will not be able to upload it outside of Chrome.

**Comment by teckno101** [comment] 2015-04-22 02:59
I think what is happening is FineUploader is detecting that it's a folder and needs to be zipped, then starts to zip it and floods the cache because it happens to be so big.
It's weird. Firefox detected it as a folder but Chrome and Safari let me upload it as one file

**Comment by rnicholus** [comment] 2015-04-22 02:59
Fine Uploader definitely does not zip anything. Do you have a sample file I can attempt to reproduce with?

**Comment by teckno101** [comment] 2015-04-22 03:00
Sure. Let me create one for you. Give me a sec

**Comment by teckno101** [comment] 2015-04-22 03:28
The file is going to take a little while to upload so I'll post the link tomorrow morning

**Comment by rnicholus** [comment] 2015-04-22 03:31
:+1:

**Comment by rnicholus** [comment] 2015-04-23 16:52
I built a sparsebundle and was unable to reproduce the issue. So, without further information or a test file to examine further, I'll have to close this. If more information is added in the future, this can be reopened.

**Closed by rnicholus** 2015-04-23 16:52 UTC
Labels: waiting for feedback
