### ISSUE TITLE
FineUploader S3 Chunk Size of 0 Occasionally

### ISSUE THREAD

**Issue by andypryor** [FineUploader/fine-uploader#1510] opened 2015-12-30 05:49 UTC
We're getting an error from S3 with a chunk size of 0 occasionally across our clients.  It isn't reproducible easily,  and will usually not happen on the second upload attempt.  We've upgraded to 5.4.1,  we previously saw the error on 5.1.3 as well. 

## Error Message
    <Error>
       <Code>EntityTooSmall</Code>
       <Message>Your proposed upload is smaller than the minimum allowed size</Message>
       <ProposedSize>0</ProposedSize>
       <MinSizeAllowed>5242880</MinSizeAllowed>
       <PartNumber>1</PartNumber>
    </Error>

 - XhrResponseStatus=400 
 - XhrTimeout=0 
 - XhrReadyState=4

## Browser
It's occurred mostly on Windows/Chrome.  Here's an example user agent

`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36`

## Chunking configuration

    chunking: {
        enabled: true,
        partSize: 10 * 1000000, //10MB
        concurrent: {
            enabled: true,
        },
    },

I feel like the concurrent chunking might be causing some issues?  I did see a similar report a problem on an older version [discussed here][1].  Has anyone ever encountered this or have any advice for troubleshooting?

  [1]: https://github.com/FineUploader/fine-uploader/issues/937#issuecomment-41418760

**Comment by rnicholus** [comment] 2015-12-30 05:55
Can you link to the exact comment where this was mentioned in #937?

**Comment by rnicholus** [comment] 2015-12-30 05:59
>I feel like the concurrent chunking might be causing some issues

Have you turned off concurrent chunking and attempted to reproduce?

**Comment by rnicholus** [comment] 2015-12-30 06:01
>will usually not happen on the second upload attempt

Fine Uploader, by default, will auto-retry. By "the second upload attempt" do you mean the next auto-retry? If not, please explain further.

**Comment by andypryor** [comment] 2015-12-30 16:05
@rnicholus   
> Can you link to the exact comment where this was mentioned in #937?

  Yes,  edited the [link to the comment](https://github.com/FineUploader/fine-uploader/issues/937#issuecomment-41418760).

> Have you turned off concurrent chunking and attempted to reproduce?

We've been unable to reproduce this in house actually.  I would be down to try disabling concurrent chunking for a portion of our users if we think it will help.

> Fine Uploader, by default, will auto-retry. By "the second upload attempt" do you mean the next auto-retry? If not, please explain further.

Sorry should have been more clear,  I do not mean the automatic retries.  The upload succeeds when the user re-initiates the upload workflow.

**Comment by rnicholus** [comment] 2015-12-30 16:13
So auto retries do not solve the issue? What specifically must the user do to complete the upload? 

The issue you linked to was specific to Safari, caused by a bug in the browser. This sounds different. 

I'll take a look at the code later in an attempt to determine how this might happen. Do you have browser console logs to match one of these incidents, or at least error logs by chance?

**Comment by andypryor** [comment] 2015-12-30 20:27
The automatic retries produce the same result.  I've seen it retry a few hundred times before the users just cancel the upload.  On cancel we call,

>           fineUploaderS3('cancelAll');
>           fineUploaderS3('clearStoredFiles');
>           fineUploaderS3('reset');

After this another attempt will work.   We've been trying really hard to reproduce this,  and haven't been able to so far.

**Comment by andypryor** [comment] 2015-12-30 22:31
@rnicholus   We just reproduced this,  when uploading files from a flash drive,  if you pull out the flash drive mid upload it will produce these logs.  It works the same for network shares or other non local files.  Deleting the files mid upload from a local drive doesn't seem to cause any problems though.

**Comment by rnicholus** [comment] 2015-12-31 01:50
This doesn't sound like a Fine Uploader issue, in that case. More like an issue with the user's file system. I'm going to close this then, unless you have any alternate theories. 

The error message is from AWS, and is not something we can customize. It seems to outline the issue pretty well though, without being overly specific about the root cause.

**Closed by rnicholus** 2015-12-31 01:50 UTC
Labels: waiting for feedback

**Comment by andypryor** [comment] 2016-01-07 18:46
@rnicholus   The client probably shouldn't send a request if it can't read the bytes from the file?  The only improvements I can think of would be better messaging,  and possibly including the path to the file that can't be accessed.  I'm not sure if this falls within FineUploader scope though?

Thanks for your help on this!

**Comment by rnicholus** [comment] 2016-01-08 02:31
This is likely out of the control of Fine Uploader. In fact, Fine Uploader doesn't "read" the file before it is uploaded, this would be highly inefficient. It simply passes a handle to the file off to the browser's request transport, and then asks the browser to send it off. Also, the file path is not available. 

Perhaps we can log a message that is more presumptuous, but this will inevitably backfire when our assumption doesn't match the reality in some case. Either way, there isn't much the user can do about this issue. If your users are experiencing this issue fairly regularly, you will want to consider mentioning this in your application's support area.
