### ISSUE TITLE
minSizeLimit is being applied to scaled Images

### ISSUE THREAD

**Issue by josefloreschura** [FineUploader/fine-uploader#1464] opened 2015-09-04 04:46 UTC
I set up the minSizeLimit to 3Mb for image files.

When uploading an image of 4Mb to S3, I receive this error (dev consode):
This is an unrecoverable error, we must restart the upload entirely on the next retry attempt.
Your proposed upload is smaller than the minimum allowed size.

This could probably be happening because the minSizeLimit is being sent to S3 to enforce validation and it is validating also the scaled images which are smallers.
https://github.com/FineUploader/fine-uploader/blob/master/client/js/s3/uploader.basic.js#L192

Fine Uploader version: Fine Uploader 5.3.0-8
Browser: Chrome
Operating system: Windows

**Comment by rnicholus** [comment] 2015-09-04 17:17
Yes, this is most likely the cause. While I can certainly understand a max size limit, enforcing a minimum size limit seems uncommon. May I ask why you are using this restriction?

**Comment by josefloreschura** [comment] 2015-09-10 23:23
I want to enforce to only upload pictures with great quality and one of the ways to do it is limiting the min size. Pictures with less than 3Mb are considered low quality which I want to avoid.

**Comment by rnicholus** [comment] 2015-09-11 03:35
>Pictures with less than 3Mb are considered low quality which I want to avoid.
This really isn't true in a general sense, and I would suggest re-evaluating this logic. The size of an image does not necessarily describe its quality. In light of this, unless there is a reasonable use for limiting minimum size of scaled images, I'm going to close this case as the uploader is behaving as designed.

**Closed by rnicholus** 2015-09-11 03:35 UTC
Labels: bug, waiting for feedback

**Comment by josefloreschura** [comment] 2015-09-12 13:27
> The size of an image does not necessarily describe its quality
I agree and that's why I said it's only one way to filter the images, there are other filters.

Another reason is that the user has a max quota to upload images, let's say is 100MB. We would want to avoid the user reducing the filesize image (sacrificing quality) just to upload more images. I know images can be reduced or compressed trying to keep quality, but in fotography there is a limit you can reduce the filesize without losing quality
