### ISSUE TITLE
'Choose File' doesn't work with stock browser in Android 4.4.2

### ISSUE THREAD

**Issue by andreas-venturini** [FineUploader/fine-uploader#1376] opened 2015-03-02 11:29 UTC
Visit http://fineuploader.com/demos.html#amazon-demo with Android 4.4.2 device and stock browser and press 'Upload a file' button. The file chooser will not open.

According to http://docs.fineuploader.com/browser-support.html Android 4 stock supports S3 uploads. 

![screenshot from 2015-03-02 12 26 20](https://cloud.githubusercontent.com/assets/4801917/6439869/a10da096-c0d7-11e4-80ec-07a2a8641075.png)

**Comment by rnicholus** [comment] 2015-03-02 15:45
It doesn't look like you are using an actual Android device.  I've found the virtual devices to be unreliable. Have you verified on an actual device?

**Comment by andreas-venturini** [comment] 2015-03-03 08:56
I have tested with both, an actual Android 4.4.4 device and Android 4.4.4 virtual device, and both worked.  So I assumed that the 4.4.2 virtual device behavior would also be reproducible on an actual 4.4.2 device as the 4.4.2 virtual device was obtained from the same source (http://www.android-x86.org/download). 

I currently do not have access to an actual Android device with 4.4.2 running on it.

Also https://code.google.com/p/android/issues/detail?id=62220 suggests this might be only an issue in 4.4.(1) and 4.4.2 Android devices

**Comment by rnicholus** [comment] 2015-03-03 15:20
Sounds like it was fixed in a hotfix release after 4.4.2. I'll mark this as a browser bug and keep it open so other with a similar issue will be able to easily locate the cause. Thanks for your report.

**Comment by SinghSukhdeep** [comment] 2017-07-02 17:38
@rnicholus I believe this can be closed since it hasn't been reported by anyone else since

**Comment by rnicholus** [comment] 2017-07-02 19:20
Thanks!

**Closed by rnicholus** 2017-07-02 19:20 UTC
Labels: 3rd-party-bug, 4 - Blocked
