### ISSUE TITLE
Submit callback wrong execution order when no auto upload

### ISSUE THREAD

**Issue by bjornbos** [FineUploader/fine-uploader#1428] opened 2015-06-22 19:15 UTC
Note: I'm using version 5.2.1.

I believe the on submit callback function should look like this:

    _onSubmitCallbackSuccess: function(id, name) {
        this._onSubmit.apply(this, arguments);
        this._uploadData.setStatus(id, qq.status.SUBMITTED);
        this._onSubmitted.apply(this, arguments);
	            	
        if (this._options.autoUpload) {
            this._options.callbacks.onSubmitted.apply(this, arguments);
            this._uploadFile(id);	                
        }
        else {
            this._storeForLater(id);
            this._options.callbacks.onSubmitted.apply(this, arguments);
        }
    }

Why? Because the file id needs to be stored in the _storeForLater array before executing the custom onSubmitted event handler. In my application I don't want to use the autoUpload as there are numerous factors important when deciding to start the upload. At the moment, my custom onSubmitted event handler triggers some algorithm to check if the upload can start. Part of that check is the following:

    var filesWaiting = fineUploader.getUploads({
        status: ['submitted']
     });

     if(filesWaiting.length) {
          fineUploader.uploadStoredFiles();
     }

The problem now is that when the user selects one file, the filesWaiting array will contain one file, but as the _storeForLater array not yet, it throws an error that there are no files selected.

**Comment by rnicholus** [comment] 2015-06-23 14:37
Sorry, I'm not sure what specific problem you are trying to work around. If you can provide a clear description of the problem followed by a series of steps required to reproduce along with any code required to reproduce, that would be great.

**Comment by bjornbos** [comment] 2015-06-23 15:56
Well, basically it all comes down to the following question: Do you agree that if you get a result back from the following function

    fineUploader.getUploads({
        status: ['submitted']
    });

that you should then be able to call the following without getting an error message:

    fineUploader.uploadStoredFiles();

Because if you agree with that, then I presented a case above where this is not like that, therefore a bug, and also provided a solution for that.

**Comment by bjornbos** [comment] 2015-06-23 15:56
Check this JSFiddle:
http://jsfiddle.net/usegz49v/8/

**Comment by rnicholus** [comment] 2015-06-23 16:06
Ah, I see. Then this appears to be a duplicate of #1106. Let me know if I've missed something.

**Closed by rnicholus** 2015-06-23 16:06 UTC
Labels: waiting for feedback

**Comment by bjornbos** [comment] 2015-06-23 16:09
Confirmed duplicate. Well, at least you have a suggestion for a fix then :)
