### ISSUE TITLE
Allow custom fields to be added to resume key

### ISSUE THREAD

**Issue by nalbion** [FineUploader/fine-uploader#1755] opened 2017-02-15 06:16 UTC
## Type of issue
- [x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [ ] Traditional
- [x] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.14.0

#### Browsers where the bug is reproducible
any

#### Operating systems where the bug is reproducible
any

#### Exact steps required to reproduce the issue
- Upload part of a large file to S3 with metadata: {user: 123, project: "xyz"}
- Refresh page
- Select same file to upload, but with different meta data: {user: 456, project: "abc"}  (actually, I don't think this is possible, but a different file would be given this metadata)
- File upload continues from where it was interrupted
- When file is complete, metadata is as per original upload

#### Detailed explanation of the problem
Resumable uploads are saved to localStorage with fileName, size, uuid, modifiedDate etc, but metadata is not included.  If a different user logs in to our app, or the same user switches to a different project and resumes the upload then when complete, the file will belong to the original user/project.

The code that parses the resume data from localStorage should compare the metadata, or `onResume` should provide some way for the application to compare the metadata (`request.params`).

</details>

**Comment by rnicholus** [comment] 2017-02-15 06:28
I see your point, but we'll need to define "metadata" exactly first, in the context of Fine Uploader S3. And second, we'll need to make appropriate changes to the code that serializes data to `localStorage`. I'm a bit apprehensive about that second step, as I don't want to run the risk of running out of space, since `localStorage` space _is_ limited to about 5 MB or so.

**Comment by rnicholus** [comment] 2017-02-15 06:29
Also, this is more of a feature request than a bug. Fine Uploader S3 functions as designed here.

**Comment by nalbion** [comment] 2017-02-15 07:53
Fine Uploader allows for an optional additional `request.params` object to be configured. For S3 uploads these are implemented as metadata fields on each S3 (file) object. 

I don't imagine that storing the request params would add much overhead.  While it may bring forward the quota exceeded scenario, that possibility of running out of space was always there. Perhaps the resume feature needs configurability of max age and record count?

**Comment by rnicholus** [comment] 2017-02-15 11:18
Age of records is already a configuration point. Another tricky implementation detail: ensuring this does not break existing/persisted resumable files.

**Comment by rnicholus** [comment] 2017-06-08 06:42
Sorry, decided to not implement

**Comment by rnicholus** [comment] 2017-07-26 20:20
I'm finding a possible need to the ability to store additional data in resume record keys. So I'm going to re-open this issue.

**Comment by rnicholus** [comment] 2017-10-10 17:54
Note that this should be addressed in #1916.

**Closed** 2018-03-09 05:50 UTC
Labels: 0 - Discuss, MAY BE KILLED, S3, enhancement
