### ISSUE TITLE
Untyped exports from modules

### ISSUE THREAD

**Issue by sgwatgit** [FineUploader/fine-uploader#1785] opened 2017-03-02 15:51 UTC
## Type of issue
- [X] Bug report
- [X] Feature request

## Uploader type
- [X] Traditional
- [X] S3
- [X] Azure

<summary>Bug Report</summary>

#### Fine Uploader version
5.14.1

#### Typescript version
2.1.6

#### Browsers where the bug is reproducible
n/a

#### Operating systems where the bug is reproducible
Windows 10 Pro

#### Exact steps required to reproduce the issue
1. npm i fine-uploader --save
2. add import statement for `fine-uploader` to Typescript file in project
3. see that import is untyped

#### Detailed explanation of the problem
Should the typescript definitions type the export of the modules?

When I have this in my file
`import qq from 'fine-uploader/lib/core';`

`qq` is type `any` and I end up typing it manually

`let uploader: FineUploader.qq = new qq.FineUploader({});`

Is there currently something about the library that preventing this feature from being added?

Also in the [documentation](https://docs.fineuploader.com/features/modules.html) the recommended approach for es2015 modules and traditional endpoints is to use the following code

```
// use Fine Uploader UI for traditional endpoints
import qq from 'fine-uploader'

// You may replace "rows" w/ "legacy" or "gallery" depending on your needs
// This assumes you have a loader to handle importing css files, such as Webpack css-loader
import 'fine-uploader/lib/rows.css'

const uploader = new qq.FineUploader({...})
```

which displays the following error at the first import statement
`[ts] File 'c:/app/node_modules/fine-uploader/typescript/fine-uploader.d.ts' is not a module.`

**Comment by rnicholus** [comment] 2017-03-02 15:54
Not a TypeScript user myself, but perhaps @SinghSukhdeep can shed some light on this issue.

**Comment by sgwatgit** [comment] 2017-03-02 16:03
Here's the documentation that I think directly applies to this issue
https://www.typescriptlang.org/docs/handbook/module-resolution.html

But I've not created js libraries with typings in an npm package before, I've only benefited from other people's work :( so I don't have a ton of insight into resolutions.

**Comment by sgwatgit** [comment] 2017-03-02 16:48
It looks like we want to add

`export { qq }`

to the bottom of `typescript/fine-uploader.d.ts` which will provide a typed import.

I see that the library exposes `qq` as a global but for those of us using Typescript and es2015 modules, the above addition would be helpful.

**Comment by rnicholus** [comment] 2017-03-02 17:00
Is this issue specific to typescript? I'm importing fine uploader in several projects using es6 imports without issue

**Comment by sgwatgit** [comment] 2017-03-02 17:30
This is Typescript specific since it's all about the `fine-uploader.d.ts` which doesn't produce any actual code, it's only using to give typings support for the library.

The imports (depending on what you are using for module loading) will pull the library from the same place, which is defined in the library's `package.json` `main` property (`"main": "lib/traditional.js",`)

**Comment by rnicholus** [comment] 2017-03-02 17:35
Not sure if `export { qq }` is what we want. That will always export 'lib/traditional.js', no? What if the TypeScript app uses Fine Uploader S3? Again, not very familiar with the TS world.

**Comment by sgwatgit** [comment] 2017-03-02 18:32
Ah, good point.

The docs state this is how the azure version is imported

```
// use Fine Uploader Azure
import qq from 'fine-uploader/lib/azure'

// You may replace "rows" w/ "legacy" or "gallery" depending on your needs
// This assumes you have a loader to handle importing css files, such as Webpack css-loader
import 'fine-uploader/lib/rows.css'

const uploader = new qq.azure.FineUploader({...})
```

First changing the `fine-uploader.d.ts` export to `export { qq, FineUploader };`
Then adding these interfaces to the FineUploader namespace in `fine-uploader.d.ts`
```
interface qqAzure {
        azure: Azure
    }

    interface qqS3 {
        S3: S3
    }
```
Finally adding this file

`/lib/azure.d.ts`
```
import { FineUploader } from 'fine-uploader';

declare var qq: FineUploader.qqAzure;

export { qq };
```

Then in the app that is importing fine-uploader can use the following

```
import { qq } from 'fine-uploader/lib/azure';

let uploader = qq.azure.FineUploader({});
```

I'm sure there is a better way to structure all this stuff (possibly moving the FineUploader namespace to a separate file and creating `.d.ts` files for each export that should be available) but this should work.

**Comment by SinghSukhdeep** [comment] 2017-03-03 02:16
I'm aware of all this, but currently we haven't done any named exports for TS, currently we've just provided a compatibility for TS projects,
Named exports is something that I want to look at going further.

In the documentation we should provide more information specific to TS and how the library should be used.

Currently if you want to follow correctly, there is a file called `fine-uploader.test.ts` right next to `fine-uploader.d.ts` which demonstrates proper syntax.

Hope this helps.

**Comment by rnicholus** [comment] 2017-03-03 05:04
Do you think https://docs.fineuploader.com/features/modules.html would the the best place to locate the TS integration instructions? I'm also wondering what specific named exports you think would be appropriate in the context of TypeScript.

**Comment by SinghSukhdeep** [comment] 2017-03-05 03:08
Yes that page should work for TS instructions.

Little explanation to why things are the way they are right now:

I can easily add named exports to the def file, so something like this at the end
`export { qq, FineUploader };` would do the job and then can be imported as such

`import { qq, FineUploader } from 'fine-uploader';`

and then you may do 

`let uploader = new qq.FineUploader(uiOptions);`

But even then the type of variable `uploader` here will be `any` since the constructor doesn't return anything and cannot return anything as long as we're using a `new` keyword.

This is a TypeScript rule that **only a void function can be called with the `new` keyword.**

All of these things came into my attention while I was writing the definitions and since the original syntax is with the use of `new` keyword, I had to keep the def that way and return void from constructors.

So in order to get proper tooling and all the TS goodies, you'll have to do

`let uploader: FineUploader.qq = new qq.FineUploader(uiOptions);`

Another problem with named exports that I have right now is with Rollup. (I can explain that later)
Which is what most of the Angular 2/ Typescript based projects use to generate production builds

I'll have to make sure that named exports work properly with Rollup before I can add it.

**Comment by rainstormza** [comment] 2017-03-10 14:38
@sgwatgit Do you use fine-uploader with angular-cli ?

**Comment by sgwatgit** [comment] 2017-03-10 14:48
I was attempting to, yes.

**Comment by rainstormza** [comment] 2017-03-10 14:58
@sgwatgit I try it with angular-cli but it seem doesn't work for me
Could you please show me the instruction ?

my code 

```
import { Component, OnInit } from '@angular/core';
declare var qq:any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'app works!';

  constructor() { }

  ngOnInit() {
  	let uploader = new qq.FineUploader({

  	});
  }
}
```
Error 
EXCEPTION: Error in :0:0 caused by: Cannot find template script at ID 'qq-template'!


thanks

**Comment by rnicholus** [comment] 2017-03-10 15:40
If you are using Fine Uploader UI, you need a template. See https://docs.fineuploader.com/branch/master/features/styling.html or the demos on the home page.

**Comment by rainstormza** [comment] 2017-03-11 01:45
@rnicholus I try to chnage 
`<script type="text/template" id="qq-template-gallery">`
to
`<div id="qq-template-gallery">`

but upload page not appear

**Comment by SinghSukhdeep** [comment] 2017-03-11 01:57
@rainstormza can you show me your entire component code

**Comment by rnicholus** [comment] 2017-03-11 01:57
The error indicates the template is not on your page, so you'll want to next figure out why the template is not available at the time the Fine Uploader instance is created.

**Comment by SinghSukhdeep** [comment] 2017-03-11 02:06
[Here ](https://github.com/FineUploader/fine-uploader/blob/develop/client/typescript/fine-uploader.test.ts )is a sample syntax for TypeScript.
More importantly you need `/// <reference types="fine-uploader" />` at the top of your component file.
and try to use variable declaration like this 

```
uploader: FineUploader.qq;
uiOptions: FineUploader.UIOptions;
coreEvents: FineUploader.CoreEvents;
```
add some UI options like this
```
this.uiOptions = {
    element: document.getElementById('fine-uploader-manual-trigger'),
    template: "qq-template-manual-trigger"
}
```
then initialize FineUploader like this

```
this.uploader = new qq.FineUploader(this.uiOptions);
```

**Comment by rnicholus** [comment] 2017-03-11 02:09
Ideally there would be an Angular implementation of the UI portion of Fine Uploader, similar to [React Fine Uploader](https://github.com/FineUploader/react-fine-uploader) and [Vue Fine Uploader](https://github.com/FineUploader/vue-fineuploader). But, for now, you'll just have to ensure the template is in the DOM before you instantiate Fine Uploader UI.

**Comment by rainstormza** [comment] 2017-03-11 02:18
so this my step and my code

ng new new-project // for create project using angular-cli
npm install fine-uploader --save // install fine-uploader to my angular-cli project

import css and js file into project like this
.angular-cli.json file

     ```
 "styles": [
        "styles.css",
        "../node_modules/fine-uploader/fine-uploader/fine-uploader-gallery.min.css"
      ],
      "scripts": [
        "../node_modules/fine-uploader/fine-uploader/fine-uploader.min.js"
```


app.component.ts file

```
/// <reference types="fine-uploader" />
import { Component, OnInit } from '@angular/core';
// declare var qq:any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  // title = 'app works!';

  	uploader: FineUploader.qq;
	uiOptions: FineUploader.UIOptions;
	coreEvents: FineUploader.CoreEvents;


  constructor() { }

  ngOnInit() {
  	/**
	 * Prepare/set options for the core + UI FineUploader
	 */
	this.uiOptions = {
	    element: document.getElementById('fine-uploader-gallery'),
	    template: "qq-template-gallery"
	}

	/**
	 * Instantiate the FineUploader and pass in the uiOptions
	 */
	let uploader: FineUploader.qq = new qq.FineUploader(this.uiOptions);
	  }
	}
```

app.componet.html file

```
<!-- Fine Uploader Gallery template
    ====================================================================== -->
    <script type="text/template" id="qq-template-gallery">
        <div class="qq-uploader-selector qq-uploader qq-gallery" qq-drop-area-text="Drop files here">
            <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
                <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
            </div>
            <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
                <span class="qq-upload-drop-area-text-selector"></span>
            </div>
            <div class="qq-upload-button-selector qq-upload-button">
                <div>Upload a file</div>
            </div>
            <span class="qq-drop-processing-selector qq-drop-processing">
                <span>Processing dropped files...</span>
                <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
            </span>
            <ul class="qq-upload-list-selector qq-upload-list" role="region" aria-live="polite" aria-relevant="additions removals">
                <li>
                    <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
                    <div class="qq-progress-bar-container-selector qq-progress-bar-container">
                        <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
                    </div>
                    <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                    <div class="qq-thumbnail-wrapper">
                        <img class="qq-thumbnail-selector" qq-max-size="120" qq-server-scale>
                    </div>
                    <button type="button" class="qq-upload-cancel-selector qq-upload-cancel">X</button>
                    <button type="button" class="qq-upload-retry-selector qq-upload-retry">
                        <span class="qq-btn qq-retry-icon" aria-label="Retry"></span>
                        Retry
                    </button>

                    <div class="qq-file-info">
                        <div class="qq-file-name">
                            <span class="qq-upload-file-selector qq-upload-file"></span>
                            <span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span>
                        </div>
                        <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                        <span class="qq-upload-size-selector qq-upload-size"></span>
                        <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">
                            <span class="qq-btn qq-delete-icon" aria-label="Delete"></span>
                        </button>
                        <button type="button" class="qq-btn qq-upload-pause-selector qq-upload-pause">
                            <span class="qq-btn qq-pause-icon" aria-label="Pause"></span>
                        </button>
                        <button type="button" class="qq-btn qq-upload-continue-selector qq-upload-continue">
                            <span class="qq-btn qq-continue-icon" aria-label="Continue"></span>
                        </button>
                    </div>
                </li>
            </ul>

            <dialog class="qq-alert-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">Close</button>
                </div>
            </dialog>

            <dialog class="qq-confirm-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">No</button>
                    <button type="button" class="qq-ok-button-selector">Yes</button>
                </div>
            </dialog>

            <dialog class="qq-prompt-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <input type="text">
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">Cancel</button>
                    <button type="button" class="qq-ok-button-selector">Ok</button>
                </div>
            </dialog>
        </div>
    </script>

```


my error console

```
EXCEPTION: Error in :0:0 caused by: Cannot find template script at ID 'qq-template-gallery'!
ErrorHandler.handleError @ vendor.bundle.js:53400
vendor.bundle.js:53402 ORIGINAL EXCEPTION: Cannot find template script at ID 'qq-template-gallery'!
ErrorHandler.handleError @ vendor.bundle.js:53402
vendor.bundle.js:53405 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ vendor.bundle.js:53405
vendor.bundle.js:53406 Error: Cannot find template script at ID 'qq-template-gallery'!
    at J (eval at webpackJsonp.526.module.exports (http://localhost:4201/scripts.bundle.js:28:8), <anonymous>:6:1240) [angular]
    at new qq.Templating (eval at webpackJsonp.526.module.exports (http://localhost:4201/scripts.bundle.js:28:8), <anonymous>:6:4293) [angular]
    at new qq.FineUploader (eval at webpackJsonp.526.module.exports (http://localhost:4201/scripts.bundle.js:28:8), <anonymous>:5:27169) [angular]
    at AppComponent.webpackJsonp.436.AppComponent.ngOnInit (http://localhost:4201/main.bundle.js:69:24) [angular]
    at Wrapper_AppComponent.ngDoCheck (/AppModule/AppComponent/wrapper.ngfactory.js:22:53) [angular]
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.detectChangesInternal (/AppModule/AppComponent/host.ngfactory.js:28:26) [angular]
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4201/vendor.bundle.js:72629:14) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4201/vendor.bundle.js:72824:44) [angular]
    at ViewRef_.detectChanges (http://localhost:4201/vendor.bundle.js:54710:20) [angular]
    at http://localhost:4201/vendor.bundle.js:36624:67 [angular]
    at Array.forEach (native) [angular]
    at ApplicationRef_.tick (http://localhost:4201/vendor.bundle.js:36624:25) [angular]
    at ApplicationRef_._loadComponent (http://localhost:4201/vendor.bundle.js:36599:14) [angular]
    at ApplicationRef_.bootstrap (http://localhost:4201/vendor.bundle.js:36587:14) [angular]
ErrorHandler.handleError @ vendor.bundle.js:53406
vendor.bundle.js:53409 ERROR CONTEXT:
ErrorHandler.handleError @ vendor.bundle.js:53409
vendor.bundle.js:53410 DebugContext
ErrorHandler.handleError @ vendor.bundle.js:53410
polyfills.bundle.js:2794 Unhandled Promise rejection: Error in :0:0 caused by: Cannot find template script at ID 'qq-template-gallery'! ; Zone: <root> ; Task: Promise.then ; Value: ViewWrappedError Error: Error in :0:0 caused by: Cannot find template script at ID 'qq-template-gallery'!
    at ViewWrappedError.ZoneAwareError (http://localhost:4201/polyfills.bundle.js:3236:33)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4201/vendor.bundle.js:25017:16)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4201/vendor.bundle.js:25082:16)
    at new ViewWrappedError (http://localhost:4201/vendor.bundle.js:53783:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:4201/vendor.bundle.js:72854:23)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4201/vendor.bundle.js:72827:18)
    at ViewRef_.detectChanges (http://localhost:4201/vendor.bundle.js:54710:20)
    at http://localhost:4201/vendor.bundle.js:36624:67
    at Array.forEach (native)
    at ApplicationRef_.tick (http://localhost:4201/vendor.bundle.js:36624:25)
    at ApplicationRef_._loadComponent (http://localhost:4201/vendor.bundle.js:36599:14)
    at ApplicationRef_.bootstrap (http://localhost:4201/vendor.bundle.js:36587:14)
    at http://localhost:4201/vendor.bundle.js:36399:89
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (http://localhost:4201/vendor.bundle.js:36399:42)
consoleError @ polyfills.bundle.js:2794
polyfills.bundle.js:2796 ZoneAwareError
```

**Comment by rnicholus** [comment] 2017-03-11 02:23
@rainstormza The issue is likely due to the fact that the template is not in the DOM when your Fine Uploader instance is created. So either the `<script>` with the template is _never_ added to the DOM/page, or it is added before Fine Uploader is instantiated. I'm not very familiar with Angular 2, so I can't assist much more with that. @SinghSukhdeep is much more knowledgeable in this area.

**Comment by SinghSukhdeep** [comment] 2017-03-11 02:50
@rainstormza you can't use the `<script>` tag in a component's html. Angular considers it unsafe.
Change that to a div and try

**Comment by rainstormza** [comment] 2017-03-11 03:01
`<div id="qq-template-gallery">`

try div but error still appear

EXCEPTION: Error in :0:0 caused by: Cannot set property 'innerHTML' of null
ErrorHandler.handleError @ error_handler.js:54
(anonymous) @ application_ref.js:261
webpackJsonp.599.ZoneDelegate.invoke @ zone.js:330
onInvoke @ ng_zone.js:273
webpackJsonp.599.ZoneDelegate.invoke @ zone.js:329
webpackJsonp.599.Zone.run @ zone.js:126
(anonymous) @ zone.js:679
webpackJsonp.599.ZoneDelegate.invokeTask @ zone.js:363
onInvokeTask @ ng_zone.js:264
webpackJsonp.599.ZoneDelegate.invokeTask @ zone.js:362
webpackJsonp.599.Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:529
error_handler.js:56 ORIGINAL EXCEPTION: Cannot set property 'innerHTML' of null


not sure this line of code might be a probelem ?

`template: "qq-template-gallery"`

**Comment by SinghSukhdeep** [comment] 2017-03-11 03:07
@rainstormza you're doing the following

`element: document.getElementById('fine-uploader-gallery'),`

but in your code I don't see an element with this id.

add an element in your html file as
`<div id="fine-uploader-gallery"></div>`

and see if it works

**Comment by rainstormza** [comment] 2017-03-11 03:22
![screen shot 2560-03-11 at 10 13 33](https://cloud.githubusercontent.com/assets/4003032/23820084/6fb40356-0643-11e7-93c4-e3a186d4a315.png)

it works :)


    <div id="fine-uploader-gallery"></div>

I forgot this line of code , my bad 

now I can use any function of fine-uploader library right ?


anyway , do we have another way for include this library to project ?
such as create this library as a module and then we can add module in app.module.ts and use it by
angular selector like this

<fine-uploader [someoption]="test"></fine-upload>

thanks for your helping @SinghSukhdeep  @rnicholus

**Comment by rnicholus** [comment] 2017-03-11 03:23
>thanks for your helping

mai pen lai krap

**Comment by SinghSukhdeep** [comment] 2017-03-11 03:31
No that's the only way to consume FineUploader in Angular 2 project right now.
We'll look into proper Angular 2 module style consumption in future

**Comment by rnicholus** [comment] 2017-03-11 03:34
There's a lot of improvements we can make to Fine Uploader - this is one of them. My apologies in advance - I'm very deeply involved in some non-code-related commitments at the moment. It's possible I'll be able to focus more on Fine Uploader in a couple weeks again, but this may last for several months.

**Comment by SinghSukhdeep** [comment] 2017-07-27 02:49
Fixed in #1840  and released as 5.15.0

**Closed by SinghSukhdeep** 2017-07-27 02:49 UTC

**Comment by rakeshmotghare** [comment] 2017-09-07 15:19
Hi Sukhdeep, could you please fix the same issue for FineUploaderTranditional. Could you please add a type script definition file .d.ts for FineUploaderTranditional. Thanks in advance.

**Comment by rakeshmotghare** [comment] 2017-09-07 17:09
Here is the code I was using in a index.d.ts file I have created to make FineUploaderTraditional work in typescript.

export default class FineUploaderTraditional{
    constructor(obj:any);
    on(eventName:string, callBackFunction:Function):void;
}

**Comment by SinghSukhdeep** [comment] 2017-09-07 17:49
@rakeshmotghare please see https://docs.fineuploader.com/branch/master/features/modules.html
scroll down to `TypeScript + Angular version 2 and higher`
Everything is explained there.

**Comment by erensogut543** [comment] 2017-11-11 14:37
Hi everyone , I tried to integrate fineuploader to AngularJS 4 project . I integrated but I think something is missing because of  in my web page the FineUploader  takes up unnecessary space as shown below in the image . Can you help me to fix this ? 

![image](https://user-images.githubusercontent.com/30908572/32690289-865894d6-c705-11e7-9514-92e9ddba68e8.png)

/////////////////////////////////// My component.ts file /////////////////

import {FineUploader, UIOptions} from 'fine-uploader';
import {Component,  OnInit} from '@angular/core';

export class AddSalesComponent implements OnInit {
  
  uploader: FineUploader;
  uiOptions: UIOptions;
ngOnInit() {
    this.uiOptions = {
      element: document.getElementById('fine-uploader-gallery'),
      template: 'qq-template-gallery',
      autoUpload: false,
      debug: true
    };

    /**
     * Instantiate the FineUploader and pass in the uiOptions
     */
    this.uploader = new FineUploader(this.uiOptions);
}

/////////////component.html file ////////////////


    
      <div id="fine-uploader-gallery"></div>
      <div id="qq-template-gallery">
        <div class="qq-uploader-selector qq-uploader qq-gallery" qq-drop-area-text="Drop files here">
          <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
            <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
          </div>
          <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
            <span class="qq-upload-drop-area-text-selector"></span>
          </div>
          <div class="qq-upload-button-selector qq-upload-button">
            <div>Upload a file</div>
          </div>
          <span class="qq-drop-processing-selector qq-drop-processing">
                <span>Processing dropped files...</span>
                <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
            </span>

          <ul class="qq-upload-list-selector qq-upload-list" role="region" aria-live="polite" aria-relevant="additions removals">
            <li>

              <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>

              <div class="qq-progress-bar-container-selector qq-progress-bar-container">
                <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
              </div>
              <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
              <div class="qq-thumbnail-wrapper">
                <img class="qq-thumbnail-selector" qq-max-size="120" qq-server-scale>
              </div>
              <button type="button" class="qq-upload-cancel-selector qq-upload-cancel">X</button>
              <button type="button" class="qq-upload-retry-selector qq-upload-retry">
                <span class="qq-btn qq-retry-icon" aria-label="Retry"></span>
                Retry
              </button>

              <div class="qq-file-info">
                <div class="qq-file-name">
                  <span class="qq-upload-file-selector qq-upload-file"></span>
                  <span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span>
                </div>
                <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                <span class="qq-upload-size-selector qq-upload-size"></span>
                <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">
                  <span class="qq-btn qq-delete-icon" aria-label="Delete"></span>
                </button>
                <button type="button" class="qq-btn qq-upload-pause-selector qq-upload-pause">
                  <span class="qq-btn qq-pause-icon" aria-label="Pause"></span>
                </button>
                <button type="button" class="qq-btn qq-upload-continue-selector qq-upload-continue">
                  <span class="qq-btn qq-continue-icon" aria-label="Continue"></span>
                </button>
              </div>
            </li>
          </ul>

          <dialog class="qq-alert-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <div class="qq-dialog-buttons">
              <button type="button" class="qq-cancel-button-selector">Close</button>
            </div>
          </dialog>

          <dialog class="qq-confirm-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <div class="qq-dialog-buttons">
              <button type="button" class="qq-cancel-button-selector">No</button>
              <button type="button" class="qq-ok-button-selector">Yes</button>
            </div>
          </dialog>

          <dialog class="qq-prompt-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <input type="text">
            <div class="qq-dialog-buttons">
              <button type="button" class="qq-cancel-button-selector">Cancel</button>
              <button type="button" class="qq-ok-button-selector">Ok</button>
            </div>
          </dialog>
        </div>
      </div>

**Comment by SinghSukhdeep** [comment] 2017-11-12 19:24
@erensogut543 just seems like some of your own css is overriding Fineuploader styles.
Check your DOM and see what that block is and what styles are being applied on it. 
Not Fineuploader issue at all
