### ISSUE TITLE
Firefox 54 drag area flickers .qq-upload-drop-area-active

### ISSUE THREAD

**Issue by SpazzMarticus** [FineUploader/fine-uploader#1862] opened 2017-06-20 12:50 UTC
## Type of issue
- [x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.11.7 on https://fineuploader.com/demos.html
5.14.4 on custom page.

#### Browsers where the bug is reproducible
Firefox 54

#### Operating systems where the bug is reproducible
Windows 8.1

#### Exact steps required to reproduce the issue
Drag file over drop area.

#### All relevant Fine Uploader-related code that you have written
none

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
default

#### Detailed explanation of the problem
Dragging file over drop area adds and removes `.qq-upload-drop-area-active` continously.

![2017-06-20_14-42-37](https://user-images.githubusercontent.com/5716457/27333832-909e8a04-55c7-11e7-9347-152d319d4bed.gif)

</details>

**Comment by cntrytwist** [comment] 2017-06-22 21:34
I can confirm the same behavior when using Mac OS and Firefox 54.

**Comment by seisnet** [comment] 2017-06-28 07:57
me too

**Comment by SpazzMarticus** [comment] 2017-06-28 13:03
The problem is caused by [leavingDocumentOut](https://github.com/FineUploader/fine-uploader/blob/5.14.4/client/js/dnd.js#L218-L220). Once you remove this part

```js
if (qq.firefox()) {
    return !e.relatedTarget;
}
```
it works in Firefox 54 as expected, but I guess in older Firefox versions there will be problems.

**Comment by cubiclesoft** [comment] 2017-07-11 13:53
Ditto.  The flickering issue shows up in the demos in Firefox:

https://fineuploader.com/demos.html

**Comment by TonyBogdanov** [comment] 2017-08-20 12:48
+1

**Comment by maximilianschmid** [comment] 2017-09-07 06:58
+1  flickering Firefox 55.0.3 (64-Bit) on MacOS 10.11.6

**Comment by AyrtonRicardo** [comment] 2017-09-29 12:52
+1 flickering Firefox 54.0 (64-bit) Linux

**Comment by simshaun** [comment] 2017-10-09 22:03
Happens in Win/Firefox 56 as well.

**Comment by alphestdev** [comment] 2017-11-03 19:24
Very disturbing for all Firefox users. Still occurs in FF 56, FineUploader 5.15.0.

Removing 3 lines as suggested by SpassMarticus works for full js. It's more complicated removing this safely from a minified version.

Please fix.

**Comment by rnicholus** [comment] 2017-11-03 20:07
Based on the referenced PR, that fix does not reliably work. I'm personally not seeing the issue myself, but if someone contributes a PR that fixes the issue and does not cause new issues, I'll make it a priority to merge it in.

**Comment by alphestdev** [comment] 2017-11-03 21:53
@rnicholus "... but if someone contributes a PR that fixes the issue ..."? 

How long are you going to wait? It's a major issue that blocks FF users from using Drag&Drop completely. 

Multiple people are reporting this and I've just tested from a fresh VM Windows7x64 with Firefox Nightly v58. The whole drop area flickers in a loop even without mouse movement and it does nothing on drop.

**Comment by rnicholus** [comment] 2017-11-03 21:59
If it's a major issue that blocks you, then please contribute a PR and we'll go from there. And I disagree that it's a major issue that blocks FF users from using DnD completely as I said I personally am not having this issue w/ my integrations.

**Comment by cubiclesoft** [comment] 2017-11-04 05:37
I ended up rolling my own solution using a different library:  https://github.com/cubiclesoft/jquery-fancyfileuploader

The flickering issue, which I can confirm is still happening in the demo (I'm running Windows 10 Pro 64-bit + Portable Firefox 56 32-bit + a couple of popular add-ons), along with the author's intentions to no longer support Fine Uploader caused me to move away from Fine Uploader for my integrations.  jQuery isn't a terrible dependency (usually) and I happen to like my solution better since there's very little that can go wrong and it works quite well on mobile devices.

**Comment by rnicholus** [comment] 2017-11-04 11:05
It’s really quite shocking to see how many users of my hard work feel they are owed something even further in particular, as if they were somehow sending me a paycheck every two weeks. It’s quite simple: if this is important to you and you have a fix they does not break something else: issue a pull request. Or you could volunteer to help maintain the library. Or you could even volunteer to help pay AWS bills. OR, you can fork the project, fix the issue to your satisfaction, and simply use that in your project. So many options! And make no mistake about it, the library is not abandoned. In fact I have a public branch/PR in progress with many substantial additions to the library in progress that is not feature complete with docs, tests, and even updated Typescript sets. See #1917 for details. 

And again, if there are other important issues to you, the proper way to deal with them in the context of Free Open Source Software is to issue a well explained/documented/tested PR and remind the overloaded maintainer periodically, or offer to help the maintainer push the case through.

**Comment by rnicholus** [comment] 2017-11-04 11:17
So far, I see lots of people complaining about this issue, and one user even going as far as using this issue to advertise his/her own library (which is in amazingly poor taste BTW) but not a single valid PR that fixes the issue. This is not my focus at the moment (see above) but will gladly coordinate with a developer that proposes a well tested PR for the issue.

**Comment by rnicholus** [comment] 2017-11-04 11:26
And why, might you ask, do I require someone actually open a PR to fix this? Because I want someone other than myself to own the issue, since it is not an important issue for me. Having the proper perspective on FOSS makes these types of requests unnecessary though.

**Comment by rnicholus** [comment] 2017-11-18 03:33
fixed in #1946

**Closed by rnicholus** 2017-11-18 03:33 UTC
